# Generated by Django 3.2.9 on 2021-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Movie name')),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0, null=True)),
                ('watchCount', models.IntegerField(default=0, null=True)),
                ('rate', models.PositiveIntegerField(default=0, null=True)),
                ('productionDate', models.DateField(blank=True, null=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('modificationDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
